<?php

declare(strict_types=1);

/**
 * UI-chrome translations for the docs site, keyed by locale then by the English
 * source string. build.php builds a `t()` helper bound to the active locale;
 * an unmapped string (or the default locale) falls back to the English source,
 * so partial coverage degrades gracefully. Page *content* is translated as
 * markdown under docs/<locale>/ — this file is only for template-generated
 * strings (navigation, section labels, preview captions, the home page).
 */
return [
    'cs' => [
        // --- Navigation & page chrome ---------------------------------------
        'Open navigation' => 'Otevřít navigaci',
        'Close navigation' => 'Zavřít navigaci',
        'Search documentation' => 'Prohledat dokumentaci',
        'Search documentation…' => 'Prohledat dokumentaci…',
        'Cancel' => 'Zrušit',
        'Toggle theme' => 'Přepnout motiv',
        'Back to top' => 'Zpět nahoru',
        'Breadcrumb' => 'Drobečková navigace',
        'Pagination' => 'Stránkování',
        'Docs' => 'Dokumentace',
        'On this page' => 'Na této stránce',
        '← Previous' => '← Předchozí',
        'Next →' => 'Další →',
        "This page hasn't been translated yet — showing the English version." => 'Tato stránka zatím není přeložená — zobrazuje se anglická verze.',

        // --- Section names (sidebar, breadcrumb, eyebrow) -------------------
        'Start Here' => 'Začínáme',
        'Forms' => 'Formuláře',
        'Fields' => 'Pole',
        'Table' => 'Tabulka',
        'Schema' => 'Schema',
        'Sortable' => 'Sortable',
        'Core' => 'Core',
        'Boost' => 'Boost',

        // --- Preview captions (build.php $previewMeta) ----------------------
        'Form Layout' => 'Layout formuláře',
        'Sections, grid layout, toggle, textarea, and action footer.' => 'Sekce, grid layout, přepínač, textarea a patička s akcemi.',
        'Repeater' => 'Repeater',
        'Nested rows with add, remove, and reorder controls.' => 'Vnořené řádky s ovládáním přidat, odebrat a přeřadit.',
        'Table Surface' => 'Povrch tabulky',
        'Search, filters, actions, and full row rendering.' => 'Hledání, filtry, akce a plný render řádků.',
        'Selection State' => 'Stav výběru',
        'Bulk-selected rows with the active selection toolbar.' => 'Hromadně vybrané řádky s aktivním toolbarem výběru.',
        'Sub-rows' => 'Podřádky',
        'Expanded invoice line items with sortable headers, row actions, and a per-invoice subtotal.' => 'Rozbalené položky faktury s řaditelnými hlavičkami, řádkovými akcemi a mezisoučtem za fakturu.',
        'Summary Footer' => 'Souhrnná patička',
        'Per-row rollup totals, a sum + average footer, and the page/all scope toggle.' => 'Rollup součty per řádek, patička se součtem + průměrem a přepínač rozsahu stránka/vše.',
        'Flatten Mode' => 'Flatten režim',
        'Every child record rendered inline as a regular table row.' => 'Každý dětský záznam vykreslený inline jako běžný řádek tabulky.',
        'Show More' => 'Zobrazit více',
        'Limited child rows with the per-parent “show more” affordance.' => 'Omezené dětské řádky s prvkem „zobrazit více" per rodič.',
        'Sub-row Filters' => 'Filtry podřádků',
        'A per-child interactive filter bar above the sub-row table.' => 'Interaktivní lišta filtrů per dítě nad tabulkou podřádků.',
        'Sortable Table' => 'Sortable tabulka',
        'Full reorderable table rendered through the sortable runtime.' => 'Plně přeřaditelná tabulka vykreslená přes sortable runtime.',
        'Reorder Detail' => 'Detail přeřazení',
        'Closer view of row ordering and drag handles.' => 'Bližší pohled na pořadí řádků a úchyty pro tažení.',
        'Core Actions' => 'Core akce',
        'Stats, actions, and shared runtime components.' => 'Statistiky, akce a sdílené runtime komponenty.',
        'Full Color Palette' => 'Kompletní paleta barev',
        'Every Tailwind hue rendered through the canonical HasColor resolvers across solid, soft, badge, button, and text surfaces.' => 'Každý Tailwind odstín vykreslený přes kanonické HasColor resolvery napříč solid, soft, badge, button a text povrchy.',
        'Modal Surface' => 'Povrch modalu',
        'Real modal rendering from the shared core component set.' => 'Reálné vykreslení modalu ze sdílené sady core komponent.',
        'Widget Dashboard' => 'Dashboard widgetů',
        'A stats overview with sparklines and a Chart.js chart widget composed in a grid.' => 'Přehled statistik se sparkliny a Chart.js chart widgetem složeným v gridu.',
        'Chart Widget' => 'Chart widget',
        'A single chart widget with heading, description, and a live quarter filter.' => 'Jeden chart widget s nadpisem, popisem a živým filtrem kvartálu.',
        'Bar Chart Widget' => 'Bar chart widget',
        'Pure-CSS bars: vertical finance, vertical system metrics with grid lines, and horizontal progress.' => 'Čistě CSS sloupce: vertikální finance, vertikální systémové metriky s mřížkou a horizontální postup.',
        'Infolist Overview' => 'Přehled infolistu',
        'Read-only record display with sections, a column grid, and formatted text/icon/badge entries.' => 'Read-only zobrazení záznamu se sekcemi, sloupcovým gridem a formátovanými text/icon/badge entries.',
        'Infolist Entries' => 'Infolist entries',
        'Every built-in entry — text, badge, list, boolean icon, color, key-value, and repeatable — bound to one record.' => 'Každá vestavěná entry — text, badge, list, boolean ikona, barva, key-value a repeatable — navázaná na jeden záznam.',

        // --- Field-page variant previews ($fieldExtraPreviews) -------------
        'Segmented Variant' => 'Segmentovaná varianta',
        'A compact segmented control — a pill highlight slides over a shared track.' => 'Kompaktní segmentovaný ovladač — pilulkové zvýraznění klouže po sdílené dráze.',
        'Buttons Variant' => 'Tlačítková varianta',
        'Separate buttons; the selected one is filled with the accent color.' => 'Samostatná tlačítka; vybrané je vyplněné akcentovou barvou.',
        'Any Accent Color' => 'Libovolná akcentová barva',
        'Every variant tints the selected option with ->color() — here a row of danger-colored cards.' => 'Každá varianta zabarví vybranou možnost pomocí ->color() — zde řada karet v barvě danger.',
        'Sizes' => 'Velikosti',
        'The segmented and buttons variants scale with ->sm() / ->md() / ->lg().' => 'Segmentovaná a tlačítková varianta se škálují přes ->sm() / ->md() / ->lg().',

        // --- Home page ------------------------------------------------------
        'The WireStack ecosystem for Livewire' => 'Ekosystém WireStack pro Livewire',
        'Build <span class="grad">forms, tables &amp; sortable</span> UIs at lightning speed.' => 'Stavějte <span class="grad">formuláře, tabulky &amp; sortable</span> UI bleskovou rychlostí.',
        'Production-ready forms, searchable tables, drag-and-drop sorting, and a shared core runtime — documented with real screenshots captured straight from the package previews.' => 'Produkčně připravené formuláře, vyhledávatelné tabulky, drag-and-drop řazení a sdílený core runtime — dokumentované reálnými screenshoty pořízenými přímo z náhledů balíčků.',
        'Packages' => 'Balíčky',
        'Four packages, one cohesive runtime.' => 'Čtyři balíčky, jeden soudržný runtime.',
        'Compose them together or use them on their own — each builds on the shared core.' => 'Skládejte je dohromady nebo je používejte samostatně — každý staví na sdíleném core.',
        'Standalone forms, layouts, validation, and nested repeaters.' => 'Samostatné formuláře, layouty, validace a vnořené repeatery.',
        'Searchable tables, actions, filters, exports, notifications, and responsive states.' => 'Vyhledávatelné tabulky, akce, filtry, exporty, notifikace a responzivní stavy.',
        'Row and column reordering built on top of the table runtime.' => 'Přeřazování řádků a sloupců postavené nad runtime tabulky.',
        'Actions, widgets, modals, notifications, plugins, and shared foundations.' => 'Akce, widgety, modály, notifikace, pluginy a sdílené foundations.',
        'Real previews' => 'Reálné náhledy',
        'Captured from the runtime, not mocked up.' => 'Pořízené z runtime, ne namalované.',
        'Every screenshot is rendered by the actual packages, so the docs match what you ship.' => 'Každý screenshot vykreslují skutečné balíčky, takže dokumentace odpovídá tomu, co nasazujete.',
        'Forms Layout' => 'Layout formulářů',
        'Primary form rendering with sections and inputs.' => 'Primární render formuláře se sekcemi a inputy.',
        'Forms Repeater' => 'Repeater formulářů',
        'Focused nested repeater with item actions.' => 'Zaměřený vnořený repeater s akcemi položek.',
        'Table toolbar, search, filters, and rows.' => 'Toolbar tabulky, hledání, filtry a řádky.',
        'Table Selection' => 'Výběr v tabulce',
        'Bulk-selected rows with active selection state.' => 'Hromadně vybrané řádky s aktivním stavem výběru.',
        'Sortable Overview' => 'Přehled sortable',
        'Full reorderable table runtime.' => 'Runtime plně přeřaditelné tabulky.',
        'Sortable Detail' => 'Detail sortable',
        'Closer look at drag and order affordances.' => 'Bližší pohled na tažení a prvky pořadí.',
        'Core Overview' => 'Přehled core',
        'Stats and shared action primitives.' => 'Statistiky a sdílené akční primitivy.',
        'Core Modal' => 'Core modal',
        'Modal surface from the core runtime.' => 'Povrch modalu z core runtime.',
        'Docs pages' => 'Stránek dokumentace',
        'Preview states' => 'Náhledových stavů',
        'Core sections' => 'Sekcí core',
        'Getting Started' => 'Začínáme',
        'Documentation Index' => 'Rozcestník dokumentace',
        'What ships in the bundle' => 'Co je v balíčku',
        'All markdown pages from' => 'Všechny markdown stránky z',
        'Public API guides for forms, table, sortable, and core' => 'Průvodce veřejným API pro forms, table, sortable a core',
        'Real preview screenshots for key runtime states' => 'Reálné náhledové screenshoty klíčových runtime stavů',
        'Client-side search index built from rendered docs content' => 'Client-side vyhledávací index sestavený z vykresleného obsahu dokumentace',
        'Publishing target' => 'Cíl publikování',
        'Upload the contents of' => 'Nahrajte obsah',
        'to any static host — no PHP runtime is required for the published site. Just build, deploy, done.' => 'na jakýkoli statický hosting — publikovaný web nepotřebuje PHP runtime. Stačí build, deploy, hotovo.',
        'Wire ecosystem · MIT licensed.' => 'Ekosystém Wire · licence MIT.',
    ],
];
