## wire-panels

The application owner layer: one entity, declared once, with the surfaces it exposes.

- **A resource is several small contracts, not one class.** `DescribesResource` (`wire-core`) is identity — `key()`, `modelClass()`, `label()`, `pluralLabel()`, all **static** — plus whichever surfaces apply: `ProvidesResourceForm` (`wire-forms`), `ProvidesResourceInfolist` (`wire-core`, beside Infolists), `ProvidesResourceTable` (`wire-panels`). A resource implements only what it has, so a read-only log declares identity + table and a page needing a form cannot be handed one that has none.
- **Each contract ships in the package owning the type it names**, which is what keeps installs honest: a resource with a form and no list needs `wire-forms` and nothing else — identity comes from `wire-core`, which forms already requires, so it never pulls in a table package. `wire-panels` requires table + forms + core and nothing requires it.
- **Static identity, instance surfaces**, and that is mechanical not stylistic: a menu asks for a label and `ResourceRegistry::forModel()` routes a model to its owner *before anything is instantiated*, so metadata must answer without an instance. Surfaces receive a builder the caller already wired to its host (same shape as `RelationManager::table()`) and hand it back.
- **Use `DescribesRecords` and declare only `modelClass()`.** Key, label and plural derive from the model (`App\Models\OrderLine` → `order-lines` / `Order Line` / `Order Lines`, irregular plurals via the inflector), so the key the registry routes on and the label a menu shows cannot drift. Override one answer without restating the rest. A resource over a non-Eloquent `DataSource` returns `null` and derives from its own class name; it registers and lists normally, it just is not findable by model.
- **Register in `config('wire-core.resources')`**, or `app(ResourceRegistry::class)->registerMany([...])` at runtime. Re-registering one class is a no-op (config merging and a twice-booted provider both do it); two different classes on one key throws, because the second would silently take over routing for the first. It is a registry, **not a panel** — no routing, no URL shell, no navigation tree — and everything it answers comes off the static contract, so building a menu never composes a table.
- **`ListPage` composes `WithTable`**, so polling, row partials, gestures and exports arrive unchanged. Set `protected static ?string $resource` and the heading defaults to the plural label; or write your own `table()` and use no resource at all — both paths are first class. A page left *half* declared (no resource **and** no `table()`, or a resource with no `ProvidesResourceTable`) throws rather than rendering an empty table, because empty reads as "no records" instead of as a mistake. Pages own no routing; mount them like any Livewire component.
- **Four pages, all standalone-capable.** `ListPage` (`WithTable`), `CreatePage` / `EditPage` (`WithForms`), `ViewPage` (renders an `Infolist`, composes **no** host trait — read-only means no state to bind and nothing to submit). Set `protected static ?string $resource`, or build the surface on the page and use no resource; both are first class. A page left *half* declared throws rather than rendering empty, because empty reads as "nothing here" instead of as a mistake.
- **Edit and view take a record KEY, not a model.** `@@livewire(EditOrder::class, ['record' => $order->getKey()])`. Mount arguments land in the Livewire snapshot, so a hydrated model there is larger than the key and stale by the next request; the key travels and `resolveRecord()` looks it up per request. Override it for a soft-delete scope, a tenant guard or a non-Eloquent source. A resource with `modelClass() === null` cannot resolve a key and says so.
- **One `form()` serves create and edit** — a create form and an edit form that drift apart is the failure the shape prevents. Persistence stays the form's (`Form` owns validate → mutate → hooks → persist → notify); the page binds the model and calls `save()`. Non-Eloquent writes go through `Form::using()` in the resource's own `form()`, and the pages are unchanged.
- **The page owns host wiring, the resource does not.** Create/Edit declare `public ?array $data` and apply `statePath('data')` before handing the form to the resource — the same division that lets `table()` know nothing about the component rendering it. A resource needing another path sets one in `form()`, which runs after and wins.
- **Every new concrete `WithTable`/`WithForms` host needs a `phpstan.neon` excludePaths entry** (runtime magic: `$this->form` comes from `WithForms::__get`). `ViewPage` is deliberately not on that list — composing no host trait is what keeps it analysable, and that is the test of whether a page belongs there.
